version: "3.7"
services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=wisely_test
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      - DATABASE_CONNECTION_STRING=postgresql://postgres:P@ssw0rd@localhost:5432/wisely_test
      - NODE_ENV=development
      - APP_ENV=development
      - PORT=8080
      - LOG=debug
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - "9090:8080"
    volumes:
      - ./api:/app
      - /app/node_modules
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    ports:
      - "8080:8080"
      - "8081:8081"
